apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pong
  annotations:
    kubernetes.io/ingress.global-static-ip-name: pong
    networking.gke.io/managed-certificates: pong
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: pong
      port:
        number: 80